apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pyql-cluster
spec:
  selector:
    matchLabels:
      app: pyql-cluster # has to match .spec.template.metadata.labels
  serviceName: "pyql-cluster"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: pyql-cluster # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: pyql-cluster
        image: joshjamison/pyql-cluster:alpha0.038
        envFrom:
          - configMapRef:
              name: pyql-cluster-config
          - secretRef:
              name: pyql-cluster-join-token
        env:
          - name: PYQL_TYPE
            value: K8S
          - name: PYQL_CLUSTER_ACTION
            value: join
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: /cluster/pyql/ready
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: pyql-cluster-db
          mountPath: /mnt/pyql-cluster
  volumeClaimTemplates:
  - metadata:
      name: pyql-cluster-db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "pyql-pv-manual-sc"
      resources:
        requests:
          storage: 20Gi